### ISSUE TITLE
Link on blended page needs to go to plots. 

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/geomag-website#102]
On the blended page,  the link "Realtime data display" in the text at the top,  should link to 
http://geomag.usgs.gov/plots.

**Comment by lisa-usgs** [comment]
Duff says:
...the process on NewApps-2 that creates them is shut down. The last plots generated may exist somewhere, but no new ones are being created.

Therefore I'm closing this issue as irrelevant.
