### ISSUE TITLE
re-add missing publications

### ISSUE THREAD

**Issue by aclaycomb-usgs** [usgs/geomag-website#109]
Eddie, can you please add the following citation to our publications page:

Love, J. J. & Swidinsky, A., 2015. Observatory geoelectric elds induced in a two-layer lithosphere during magnetic storms, Earth Planets Space, 67, 58, doi:10.1186/s40623-015-0213-3.

And link to the article attached.

Also, please change the following citation 

Love, J. J., 2008. Magnetic monitoring of Earth and space, Physics Today, 61, 31-37.

to

Love, J. J., 2008. Magnetic monitoring of Earth and space, Physics Today, 61(2), 31-37.

Also please note that I already sent a request for publications updates on April 30.

(JLove)

**Comment by emcwhirter-usgs** [comment]
[s40623-015-0213-3.pdf](https://github.com/usgs/geomag-website/files/10332/s40623-015-0213-3.pdf)
