### ISSUE TITLE
User reported trouble loading comic book

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-website#112]
This file takes 55 seconds to load in a browser when I attempted multiple times:
  http://geomag.usgs.gov/publications/comicbook/GeomagComic.pdf

- See if there is a way to compress it.
- Add links while we're at it.

**Comment by jmfee-usgs** [comment]
I download within a few seconds:
```
$ curl -O http://geomag.usgs.gov/publications/comicbook/GeomagComic.pdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.4M  100 27.4M    0     0  5187k      0  0:00:05  0:00:05 --:--:-- 5751k
```

Which browser are you using, and does it also load slowly when you pre-download and open a local copy of the file?

**Comment by emcwhirter-usgs** [comment]
I initially tried in Chrome, Firefox and IE all at the same time. I had an independent timer running and just watched it and checked the network tab in the inspectors for Chrome and Firefox.

Running the tests now, the inspectors show much faster times ranging from ~1sec - ~15sec. So I suspect it is being cached now. The file is almost 30M, but compressing it appears to make it grainy.

**Comment by lisa-usgs** [comment]
Replaced with ~5MB version PDF.
