### ISSUE TITLE
missing data acknowledgement

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#135]
I just noticed that in the process of updating our 'data download' page on geomag.usgs.gov to accommodate the sunsetting of magweb, it appears that we have removed some language that we used to have out there about use of USGS geomagnetic data and acknowledging that use in any publications that use our data.  Here's what it used to say (still available on http://ehpd-geomag.cr.usgs.gov/products/downloads.php)

"Access to the data is provided as-is, without any additional promises to respond quickly to outages, data quality, etc. We request that you acknowledge the USGS Geomagnetism Program in all published documents which make use of our data. Thank you for your interest in the USGS."   

I would like to have similar language added back in somewhere up front where the user can't miss it, possibly in the leading yellow box on the new Downloads page.(http://geomag.usgs.gov/products/downloads.php)

We could change the last sentence in the yellow box from "Thank you for your interest in our program." to:

"USGS Geomagnetism Program data are made available as-is and without any guarantees of continuity and quality.

Publications making use of our data should include an acknowledgment statement such as the following:

The results presented in this document rely on data collected at magnetic observatories operated by the U.S. Geological Survey (USGS, geomag.usgs.gov).  "

and maybe precede it with the heading "Data Acknowledgement".

**Comment by lisa-usgs** [comment]
Here is what the page looks like with the additional information in the yellow box at the top.  Let me know if you still want it like this, or if you'd prefer I move at least some of that text down to the bottom of the page.
![screencapture-localhost-8070-products-downloads-php-1462891868513](https://cloud.githubusercontent.com/assets/4162494/15150959/880191c8-168c-11e6-84e8-a0da56dc8867.png)

**Comment by lisa-usgs** [comment]
Done.
