### ISSUE TITLE
Need to update all references to Air Force Weather Agency and AFWA

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#137]
On the partners page (http://geomag.usgs.gov/partners.php), we need to replace "Air Force Weather Agency" with "557th Weather Wing", and replace the old AFWA logo with a new one like this: 

![image](https://cloud.githubusercontent.com/assets/14202814/11701044/90e9201e-9e8a-11e5-8bfc-5232066da346.png)

**Comment by emcwhirter-usgs** [comment]
Just to be clear, "Air Force" will not appear anywhere in the text, right? So, the sentence will read
`The USGS provides real-time magnetometer data to NOAA's Space Weather Prediction Center, the 557th Weather Wing, and NASA.`, correct?

Also, I checked the rest of the website for references to AFWA (and Air Force, and Weather Agency, and other similar terms.) The only place it appears besides the partners page is on the Del Rio page.

**Comment by cafinn-usgs** [comment]
No, I would put U.S. Air Force in front of 557th...

I didn't realize we still had a Del Rio page??
