### ISSUE TITLE
problems with logos on 'partners and customers' page

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#152]
1.  Several of the circular logos on the Geomag partners & customers page (http://geomag.usgs.gov/partners.php) are misshapen  when viewed with Mozilla firefox - they are now ovals instead of circles.  Anyone who knows anything about visual identity would not be please to see these logos with a different shape.  Can this be fixed?  Problems include:  IAGA, NSWP, and NASA. "Schlumberger" also is crammed into a smaller horizontal space than it should be.  SET's logo is barely readable on the lower line of text.

2.  Conversely, when viewed in Internet Explorer, the shapes are fine, but the logos under 'Public-Private Partnership' are all of varying sizes, with the ISTI logo completely occupying the entire page.

3.  The logos all look fine in Chrome, with the exception of the SET logo, which is perhaps smaller than it should be.

4.  NASA's logo appears twice, once under 'National' and a second time under 'Observatory Partners'.  Recommend deleting it from the latter group.  We are also missing a logo for the Bureau of Land Management (BLM) in this group.

**Comment by lisa-usgs** [comment]
Apparently this is a known problem with Firefox.  See https://support.mozilla.org/en-US/questions/1083513.  I turned on the hardware acceleration as the support suggested, but it didn't help.  I'll have to talk to the web app team to see if anyone has any suggestions.

**Comment by jmfee-usgs** [comment]
This appears related to the `display: flex` property for `.logo > a`, disabling that rule seems to fix the problem in firefox and it still works in chrome:

https://github.com/usgs/geomag-website/blob/master/src/htdocs/index.css#L38
through
https://github.com/usgs/geomag-website/blob/master/src/htdocs/index.css#L41

**Comment by lisa-usgs** [comment]
Done.
