### ISSUE TITLE
missing Abram Claycomb from "Contact Us" page

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#173]
Can we please add Abram (Abe) Claycomb to our "Contact Us" page? at
http://geomag.usgs.gov/contact.php

His phone number is 303-273-8430; email address is aclaycomb@usgs.gov.
He has a photo associated with his email account that can probably be used for the web page.
His area of expertise should be Operations/Development

Thanks.

**Comment by cafinn-usgs** [comment]
We also need to add Jason Austin, 303-273-8590, joaustin@usgs.gov. Operations.

**Comment by lisa-usgs** [comment]
I will need to receive the JPG photo file for both Abe and Jason, otherwise I can just add their names to the Contact page.

**Comment by cafinn-usgs** [comment]
Will these work?

**Comment by lisa-usgs** [comment]
I'm guessing you attached files to the issue in this interface, but I don't see them. Can you just send them to me in an email?

**Comment by lisa-usgs** [comment]
Done
