### ISSUE TITLE
error on Tucson document

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#178]
I found an error in the legal description of the 1909 Tucson observatory property, so this document needs to be replaced with the one that I have attached.  
From:
http://geomag.usgs.gov/monitoring/observatories/tucson/downloads/History_of_Tucson_Observatory.pdf

[History_of_Tucson_Observatory-revised.pdf](https://github.com/usgs/geomag-website/files/348747/History_of_Tucson_Observatory-revised.pdf)

**Comment by lisa-usgs** [comment]
Done.
