### ISSUE TITLE
need updated background sentence for Tucson observatory

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#227]
Lisa, I swear I don't know how this minor stuff gets missed.  I happened to notice that the comma separating the two phrases in the following sentence can be confusing.  I'd like to modify it to add some clarification.  Can you modify this introductory sentence from:

The Geomagnetism Program first established an observatory near Tucson in 1910, the current site, in the Saguaro National Park , was installed in 1996. 

to:
The Geomagnetism Program first established an observatory near Tucson in 1910 on what is now Morris K. Udall Regional Park.  The current site, in the Saguaro National Park , was installed in 1996. 

on this page:

https://geomag.usgs.gov/monitoring/observatories/tucson/

**Comment by lisa-usgs** [comment]
The sentence has been modified and will show up on the public website within 30 minutes.
