### ISSUE TITLE
Photos on Fredericksburg observatory web page

### ISSUE THREAD

**Issue by cafinn** [usgs/geomag-website#28]
I don't think we really need two photos of the signs at the Fredericksburg observatory.  Please delete the second to the last one (the one that has the gas station in the background) from this page:

http://dev-geomag.cr.usgs.gov/monitoring/observatories/fredericksburg/

**Comment by jmfee-usgs** [comment]
broken stylesheet link `tablist/tablist.css` should be fixed/removed
