### ISSUE TITLE
publications to add, and a few corrections

### ISSUE THREAD

**Issue by aclaycomb-usgs** [usgs/geomag-website#281]
[Peckham-Kelbert-2016-Computers-Geosciences.pdf](https://github.com/usgs/geomag-website/files/2033398/Peckham-Kelbert-2016-Computers-Geosciences.pdf)
[Pubstoadd.docx](https://github.com/usgs/geomag-website/files/2033399/Pubstoadd.docx)
[Statistical Methods.pdf](https://github.com/usgs/geomag-website/files/2033400/Statistical.Methods.pdf)
[Dst_Predictor_validation_distro_A.pdf](https://github.com/usgs/geomag-website/files/2033401/Dst_Predictor_validation_distro_A.pdf)
[Gary_Egbert_ModEM.pdf](https://github.com/usgs/geomag-website/files/2033402/Gary_Egbert_ModEM.pdf)
[Heilig-et-al-IAGA-Proceedings-2012.pdf](https://github.com/usgs/geomag-website/files/2033403/Heilig-et-al-IAGA-Proceedings-2012.pdf)
[Kelbert_et_al-2017-Methodology-Space_Weather.pdf](https://github.com/usgs/geomag-website/files/2033404/Kelbert_et_al-2017-Methodology-Space_Weather.pdf)
[Love_et_al-2017-Down-to-Earth-Space_Weather.pdf](https://github.com/usgs/geomag-website/files/2033405/Love_et_al-2017-Down-to-Earth-Space_Weather.pdf)
[Observatories USA.pdf](https://github.com/usgs/geomag-website/files/2033406/Observatories.USA.pdf)
[Sun_et_al-2015-Journal_of_Geophysical_Research.pdf](https://github.com/usgs/geomag-website/files/2036417/Sun_et_al-2015-Journal_of_Geophysical_Research.pdf)
[Pulkkinen_et_al-GIC-2017-Space_Weather.pdf](https://github.com/usgs/geomag-website/files/2036418/Pulkkinen_et_al-GIC-2017-Space_Weather.pdf)

**Comment by aclaycomb-usgs** [comment]
In-process edits
[preview_love2-JJL.pdf](https://github.com/usgs/geomag-website/files/2036423/preview_love2-JJL.pdf)

**Comment by lisa-usgs** [comment]
FYI - I've recently (last couple of years or so) learned that authors are allowed to put copies of their published papers on their own website (or agency website) before the journal allows open access, which is anywhere from immediately to 6 months to a year, depending on the journal.  BUT, we cannot put a copy of the journal's formatted PDF on our website - it has to be an unformatted version or a format the author has done themselves. I *think* it might be fine to put their formatted version on our website once they have made the publication open-access, but I'm not sure.

In any case, I wanted to let you know about that legal requirement in case any of these are journal-formatted files within the time window that the journal does not allow open access.

**Comment by aclaycomb-usgs** [comment]
Thanks, Lisa... I've forwarded that on to Jeff, and I'm awaiting his reply.

**Comment by lisa-usgs** [comment]
I did tell Jeff that recently, and he sent me a PDF for one recent paper that I forgot to check to see if it was journal formatted or not. I may have to replace that one if it is.
