### ISSUE TITLE
two broken links on FRD observatory page

### ISSUE THREAD

**Issue by cafinn** [usgs/geomag-website#29]
These two links are broken:

"Addresses on the occasion of the Completion of One-Third of a Century of Continuous Observations at the Cheltenham Magnetic Observatory of the U.S. Coast and Geodetic Survey, Cheltenham, Maryland."

http://dev-geomag.cr.usgs.gov/downloads/publications/STATUTE-66-Pg70.pdf

and

"Public Law authorizing the construction of the Fredericksburg observatory."

http://dev-geomag.cr.usgs.gov/downloads/publications/STATUTE-66-Pg70.pdf

**Comment by emcwhirter-usgs** [comment]
These links should work once the fixes from @jdbrown-usgs go through because his fixes include the missing 'downloads' folder.

**Comment by emartinez-usgs** [comment]
@emcwhirter-usgs is correct. These appear to have already been fixed.
