### ISSUE TITLE
Main "Research" page text summary should be placed first

### ISSUE THREAD

**Issue by erigler** [usgs/geomag-website#31]
The summary/overview text describing research in the USGS Geomagnetism program (look at: http://dev-geomag.cr.usgs.gov/research/) should come **before** any of the individual sub-categories found on this page. Even on a desktop web browser it looks strange for the text to be placed in the right-most column, but when the browser window shrinks below a certain size (and presumably if viewed on a mobile device, but I cannot test this), the text gets pushed all the way to the bottom of the page, which is certainly not desirable.

**Comment by lisa-usgs** [comment]
If you want the text "summary" at the top of the webpage, it should be shortened to one small paragraph.  Research shows that people will skip the text, except it's so long here that no one will realize there are items to choose from below.

Carol put in a ticket asking that the right column with the text be made wider, which I can do.

**Comment by lisa-usgs** [comment]
Made column wider in issue #44.  Will not do this until more discussion and shorter intro text.
