### ISSUE TITLE
Front page columns don't flow properly around inline Youtube movie

### ISSUE THREAD

**Issue by erigler** [usgs/geomag-website#33]
The Youtube video on the front page does not resize with changing browser windows size, and as a result, can overlap text and images in the right-hand column. I'm not sure if this is fixable, except to make the video an image+link to the actual video (my personal preference, for what it's worth, but probably not world-wide-web-standard).

**Comment by jmfee-usgs** [comment]
This is addressed by #35

**Comment by jmfee-usgs** [comment]
I believe this has been fixed.

**Comment by emartinez-usgs** [comment]
I agree this appears to have been fixed in #35.
