### ISSUE TITLE
sizing of columns

### ISSUE THREAD

**Issue by cafinn** [usgs/geomag-website#34]
The sizing of columns on some pages seems strange.  On

http://dev-geomag.cr.usgs.gov/research/

there is way too much white space for the image column on the left, and as a result the text column on the right seems squeezed in.  This should be adjusted to allow the text column to be wider.

A similar problem exists on:

http://dev-geomag.cr.usgs.gov/learn/

**Comment by emartinez-usgs** [comment]
Fixed by fdeca8bf.
