### ISSUE TITLE
Changes to research page

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#36]
1)  The left-hand column on this page:

http://dev-geomag.cr.usgs.gov/research/

contains a typo in "Earthquake Prediction".  Earthquake is misspelled as 'earhquake'.

2)  Delete the link to "Hazard Mapping" and all sub-links to those same beta hazard maps.  These are beta products that were abandoned after Jenn Gannon left, and since no one has done anything with them since, there is no sense carrying them forward until such time as we are ready to invest more time into them.

3)  Change the name of the Topic "Geomagnetically Induced Currents" to "Induction Hazards".  For now, you can leave the same text that is associated with that page, but Jeff Love will need to provide you with updated text to go there instead. You can still use the same image (of the power lines) that is associated with it now.

4) Move Earthquake Prediction down the page, after Space Climatology.  That is a really small portion of our research focus, so it shouldn't be the first thing listed after Publications.

**Comment by emartinez-usgs** [comment]
1) Can not find typo. Perhaps it was fixed previously.
2) Should the content found at /research/hazards.php also be deleted? I'm not sure what all is included with "all other sub links"; please clarify.
3) Updated text.
4) Moved link down the page.

Note: These changes won't be visible until I receive further guidance on (2) so I can complete the ticket as a whole.

**Comment by erigler** [comment]
Pardon me poking my nose in, but regarding the "Hazard Mapping" page, I agree with Carol, we shouldn't link to abandoned or stalled projects, but I would hesitate to delete the information on the actual hazards.php page.

I wonder if we can set up a kind of "internal staging and evaluation" page that isn't linked from our main pages, but where we can access projects that need attention. This would just be a very simple page that is not linked to from any of our public facing pages, that had nothing but links to various non-production web pages that needed attention. I know this consumes resources, but there are some "back-burner" projects that should not fall off our radar, even though we don't have resources to apply to them at the moment (like the hazards.php page).

Maybe I need to submit a fresh ticket.

**Comment by emartinez-usgs** [comment]
For a more generalized "back-burner" area, yes please submit a new ticket on GitHub. This area would likely not be created/populated until some later date after further discussion, but entering a ticket serves as a reminder/placeholder for future work to be done.

**Comment by erigler** [comment]
@emcwhirter-usgs  just pointed out that, through GitHub, I have easy access to the directory structure, and so can see all *.php files, even those not advertised. I will make-do with this for now, and hold off on requesting a "back-burner" links page. Thanks.

**Comment by cafinn** [comment]
1) Typo is still there, on the left-hand column on that page.  Here's a
screenshot.

2) Yes, the content found at /research/hazards.php be removed from the
public page.

What I meant by "sub-links" is that the hazard map shown on
/research/hazards.php also shows up in other places, like on the "Data and
Products" page (.../products/), where there is a link to "Real-Time
Geomagnetic Conditions", which shows the same hazard map as the one on the
research page.

**Comment by jmfee-usgs** [comment]
Typo is at https://github.com/usgs/geomag-website/pull/50/files#diff-5e0c6c1df44dd57f2f4aeae9dd88e3d9L4

**Comment by emartinez-usgs** [comment]
Updated PR.
