### ISSUE TITLE
Research links broken

### ISSUE THREAD

**Issue by cafinn** [usgs/geomag-website#37]
All of the links on the Space Weather Applications page are broken,

http://dev-geomag.cr.usgs.gov/research/spaceweather.php

and

All of the publications links on the Publications, Earthquake Prediction, GICs, Extreme Events, Magnetic Data Quality, and Space Climatology pages are broken:

http://dev-geomag.cr.usgs.gov/publications/papers.php
http://dev-geomag.cr.usgs.gov/research/geomagnetism-earthquakes.php
http://dev-geomag.cr.usgs.gov/research/GIC.php
http://dev-geomag.cr.usgs.gov/research/extreme-events.php
http://dev-geomag.cr.usgs.gov/research/magdataquality.php
http://dev-geomag.cr.usgs.gov/research/spaceclimatology.php

(and you already know about the missing movie maps)

**Comment by emartinez-usgs** [comment]
The spaceweather.php page links to /realtime which is more of a routing issue. They were already fixed.  The remaining links were all fixed by work done in usgs/geomag-website#24 by @jdbrown-USGS
