### ISSUE TITLE
Data and Products links broken

### ISSUE THREAD

**Issue by cafinn** [usgs/geomag-website#38]
These links on the Data & Products page are broken:

Real-Time HEZF Display:
http://dev-geomag.cr.usgs.gov/realtime

Magnetic Disturbance Events:
http://dev-geomag.cr.usgs.gov/storm/

Real-Time Dst Display:
http://dev-geomag.cr.usgs.gov/realtime/dst

All Beta Products:
http://dev-geomag.cr.usgs.gov/products/beta.php

**Comment by emartinez-usgs** [comment]
These were fixed by routing updates.
