### ISSUE TITLE
Update $CONTACT_URL and $CONTACT configuration.

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-website#51]
Update site configuration of `$CONTACT_URL` to be a mailto link.
Update site configuration of `$CONTACT` to default to `geomagdata@usgs.gov`.
Remove `$CONTACT` configuration from pages that use default.

**Comment by emartinez-usgs** [comment]
The following pages specify `$CONTACT`, but use the default. Please remove.

src/htdocs/monitoring/index.php
src/htdocs/monitoring/instrumentation.php
src/htdocs/monitoring/links.php
src/htdocs/monitoring/observatories/barrow/index.php
src/htdocs/monitoring/observatories/boulder/index.php
src/htdocs/monitoring/observatories/college/index.php
src/htdocs/monitoring/observatories/deadhorse/index.php
src/htdocs/monitoring/observatories/delrio/index.php
src/htdocs/monitoring/observatories/fredericksburg/index.php
src/htdocs/monitoring/observatories/fresno/index.php
src/htdocs/monitoring/observatories/guam/index.php
src/htdocs/monitoring/observatories/honolulu/index.php
src/htdocs/monitoring/observatories/index.php
src/htdocs/monitoring/observatories/newport/index.php
src/htdocs/monitoring/observatories/sanjuan/index.php
src/htdocs/monitoring/observatories/shumagin/index.php
src/htdocs/monitoring/observatories/sitka/index.php
src/htdocs/monitoring/observatories/sitka/sow/index.php
src/htdocs/monitoring/observatories/stennis/index.php
src/htdocs/monitoring/observatories/tucson/index.php
src/htdocs/monitoring/operations.php
src/htdocs/products/downloads.php
src/htdocs/products/index.php
src/htdocs/products/models.php
src/htdocs/products/otherdata.php
src/htdocs/products/realtime/index.php
src/htdocs/services.php
