### ISSUE TITLE
wrong menu on left side of "Magnetic Disturbance Movies" page

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#82]
The menu on the left side of this page points to the main Geomag menu (Monitoring/Data & Products/Research...) instead of first having the sub-menu of Research topics (Research -> Publications/ Geomagnetically Induced Currents/ etc.).

Most of the other Research pages have this sub-menu, but this one does not.  (Publications doesn't have the sub-menu, and neither does the Regional Conductivity Maps page.  I can see why on the latter - not enough room for both.  Not sure what the logic is on not including it on the Publications page.)

**Comment by emartinez-usgs** [comment]
Carol will talk this over with Geomag to determine if movies content should be moved from the "research" to the "publications" section. Otherwise we can create a publications section navigation and add movies to that section nav.

**Comment by cafinn-usgs** [comment]
I talked to Jeff and he strongly feels that the movies belong directly under Publications, since they are actually tied to one of his publications.  I suggest we add "Movies" as a menu item under Publications, along with Papers, Abstracts, and Charts, which BTW, appear to have been lost from the transition from old to new.  (see http://geomag.usgs.gov/publications/papers.php)

**Comment by emcwhirter-usgs** [comment]
The Movies page now has the same left navigation as the other items in the publications directory from usgs/geomag-website#86. So there is nothing remaining that "needs" to be done. We should verify after that ticket is merged.

**Comment by cafinn-usgs** [comment]
So I still can't see this and a few others of the most recent fixes.  Why
not?  It hasn't been 'merged' yet?

**Comment by emcwhirter-usgs** [comment]
Correct. They will become visible when they are merged. This is part of our work-flow to ensure that more than 1 set of eyes has looked at code before it is released.

**Comment by cafinn-usgs** [comment]
Ok, I still don't see a separate Publications page, or the Movies page
underneath it.  When will this be merged?

**Comment by emcwhirter-usgs** [comment]
We just finished a sprint on another project yesterday afternoon, and most of the rest of the team has off today, so it should be done early next week, hopefully.
