### ISSUE TITLE
Changes needed on "Contact Us" page

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#83]
(1) We need to add an entry for Anna Kelbert to this page.

(2) We should delete the addresses for the College and Fredericksburg observatories on the right-hand side.  Those are relics from when we had employees stationed at those locations.

**Comment by emcwhirter-usgs** [comment]
For (1), Anna's picture and information are on the currently live geomag site: http://geomag.usgs.gov/contact.php
