### ISSUE TITLE
access to Geomag home page

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#84]
I can't believe I have to scroll all the way to the bottom of each page and search for the little "Home" link in order to get back to the Geomagnetism Program home page!  That is crazy!  There should be a link right at the top, in connection with the words "National Geomagnetism Program" in the banner.

I'm also not crazy about having to scroll all the way to the bottom to find the very faint links for "Contact Us" and "About Us".  Are we trying to keep people from finding out about us?  Ideally those should all be back up at the top in the banner line.

Alternatively, add those as links in the menu bar that is on the left-hand side of most pages.

**Comment by hasimpson-usgs** [comment]
You click on the USGS image.

On Tue, Sep 15, 2015 at 6:02 PM, cafinn-usgs <notifications@github.com>
wrote:

> I can't believe I have to scroll all the way to the bottom of each page
> and search for the little "Home" link in order to get back to the
> Geomagnetism Program home page! That is crazy! There should be a link right
> at the top, in connection with the words "National Geomagnetism Program" in
> the banner.
>
> I'm also not crazy about having to scroll all the way to the bottom to
> find the very faint links for "Contact Us" and "About Us". Are we trying to
> keep people from finding out about us? Ideally those should all be back up
> at the top in the banner line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usgs/geomag-website/issues/84>.
>



-- 
Hal Simpson
IT Specialist
USGS Geomagnetism Program
Office:303-273-8459
Email:hasimpson@usgs.gov

**Comment by cafinn-usgs** [comment]
That should take me to the usgs home page, not the geomag home page.

**Comment by cafinn-usgs** [comment]
So if we can't change the way this works (clicking on the USGS image to get to "geomag.usgs.gov"), can we add these links to the right-hand side of the pages, like we have now?
![capture-usgshome](https://cloud.githubusercontent.com/assets/14202814/9911914/cac73570-5c61-11e5-83b6-88e812657f37.PNG)

**Comment by lisa-usgs** [comment]
We are using a new template that is sorta approximately like the new USGS template about to go live, so we cannot add or change anything that would be at odds with that template.

**Comment by lisa-usgs** [comment]
Carol - I had a discussion with Linda and Jill about the new template that we're using for Geomag, Landslides, and Earthquake. They said that the web development team was charged with creating the template, and they (Jill and Linda) were not pleased that I brought the issue up again. They said it will not be changed... period.  So I'll close this ticket.
