### ISSUE TITLE
Learn - Further Reading - Aurora

### ISSUE THREAD

**Issue by cafinn-usgs** [usgs/geomag-website#85]
There is a whole lotta white space here between the next topic, just because the image to the right is too large.  Why not reduce the size of that image in order to make the page more readable?  (there are other images on the same page of varying size)  It's also not the highest quality image.  Surely we can find something better than that.

http://prod-geomag.cr.usgs.gov/learn/reading.php

**Comment by cafinn-usgs** [comment]
Here's a better image to use.  Jeff Love says, "They will have to shrink this down, as it is very high resolution. I bought rights to this image."
![fig1-492942259](https://cloud.githubusercontent.com/assets/14202814/9911849/6226fa50-5c61-11e5-81c6-caa816519d6d.jpg)

**Comment by lisa-usgs** [comment]
We'll need the information about the author, organization, license.

**Comment by cafinn-usgs** [comment]
See attached.

**Comment by jmfee-usgs** [comment]
@cafinn-usgs , I don't think attachments are added to the github issue.  If you open this issue in a browser, you can drag attachments into a new comment.

**Comment by cafinn-usgs** [comment]
Hmm.  They are .pdf files, and it says it only supports png, gif, and jpg files.  Got another idea?

**Comment by emcwhirter-usgs** [comment]
Send the pdf to me. I'll get the information on here.

**Comment by cafinn-usgs** [comment]
I just sent them to Jeremy and Eric.

**Comment by jmfee-usgs** [comment]
I'm attaching a lower resolution of the photo, I don't think we're supposed to make the original available...

This is the attribution the license requires, not sure if we want to prefix it as "Copyright: ..." to make it clear to users this is not like other content on the site:
"[Jon Hilmarsson/Getty Images]"

![6226fa50-5c61-11e5-81c6-caa816519d6d_web](https://cloud.githubusercontent.com/assets/1717896/9916946/3bbb8a3c-5c7c-11e5-8453-f7f23d286406.jpg)

**Comment by lisa-usgs** [comment]
The standard is:


Caption is written here. Photo credit:  name, organization.

-Lisa
—



On Sep 16, 2015, at 2:11 PM, Jeremy Fee <notifications@github.com> wrote:

I'm attaching a lower resolution of the photo, I don't think we're supposed to make the original available...

This is the attribution the license requires, not sure if we want to prefix it as "Copyright: ..." to make it clear to users this is not like other content on the site:
"[Jon Hilmarsson/Getty Images]"

 <https://cloud.githubusercontent.com/assets/1717896/9916946/3bbb8a3c-5c7c-11e5-8453-f7f23d286406.jpg>

**Comment by jmfee-usgs** [comment]
This is the original page including caption:
http://www.gettyimages.com/detail/photo/aurora-explosion-royalty-free-image/492942259

The getty images license terms specify the name/organization format:
```Format: [Photographer Name/Getty Images]```
http://www.gettyimages.com/license-info

```[Jon Hilmarsson/Getty Images]```

**Comment by lisa-usgs** [comment]
Hmm, not sure how to resolve that one... when our standard image credit has one format and the license for using a 3rd party image requires a different format.  I guess we use their form to avoid any misuse of the license.
